import Erdos260.Tier2TopBandReadTail

open Erdos260.Tier2TopBandReadTail

#print axioms topband_unrouted_empty
#print axioms topband_unlabeled_empty
#print axioms topband_uncovered_empty
#print axioms topband_mass_dichotomy
#print axioms readtail_pushforward_mass_preserving
#print axioms readtail_fibre_weight_le
#print axioms readtail_fibre_card_le_of_coords
#print axioms readtail_fibre_weight_eq_pushforward
